project:
  type: website
  output-dir: docs
  render: 
      - "*.qmd"
      - "!papers"
      - "!epid592"
      - "!epid594"
      - "!pubhlth405"
      - "!talks"
website:
  title: "Zelnotes"
  sidebar:
      style: "docked"
      contents: auto


execute:
  freeze: auto

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    bibliography: /Users/jzelner/repos/bibtex-library/jz_library.bib
    resource-path: 
          - "images"

