project:
  title: "Zelnotes"
  type: website
  lib-dir: css
  #output-dir: docs
  render: 
      - "*.qmd"
      - "!papers"
      - "!epid592"
      - "!pubhlth405"
      - "!talks"
      
website:
  title: "Zelnotes"
  site-url: https://zelnotes.io
  favicon: "assets/epibayeslogo_cropped.png"
  open-graph: true
  sidebar:
      style: "docked"
      contents:
        - section: Courses
          contents:
            - epid594/index.qmd
            - epid684/index.qmd
        - posts/index.qmd
      collapse-level: 3
      logo: "assets/epibayeslogo_cropped.png"
      title: "Zelnotes"
  repo-url: https://github.com/jzelner/zelnotes 
  google-analytics: "G-4J38PX7FF5"

format:
  html:
    theme: 
      light: cerulean 
      dark: [cerulean, theme-dark.scss]
    css: styles.css
    toc: true
    bibliography: 
      - /Users/jzelner/repos/bibtex-library/jz_library.bib
      - epid684/refs.bib
    resource-path: 
          - "images"

execute: 
  freeze: auto