project:
  title: "Zelnotes"
  type: website
  #output-dir: docs
  render: 
      - "*.qmd"
      - "!papers"
      - "!epid592"
      - "!pubhlth405"
      - "!talks"
      
website:
  title: "Zelnotes"
  site-url: https://zelnotes.io
  favicon: "assets/epibayeslogo_cropped.png"
  open-graph: true
  sidebar:
      style: "docked"
      contents:
        - section: Courses
          contents:
            - section: EPID 684 - Spatial Epidemiology
              contents:
                - epid684/index.qmd
                - epid684/policies.qmd
                - epid684/roadmap-project/index.qmd
            - section: EPID 592 - Spatial Epidemiology (Online MPH)
              contents:
                - epid594/index.qmd
        - posts/index.qmd
      collapse-level: 3
      logo: "assets/epibayeslogo_cropped.png"
      title: "Zelnotes"
  repo-url: https://github.com/jzelner/zelnotes 

format:
  html:
    theme: "cerulean" 
    css: styles.css
    toc: true
    bibliography: 
      - /Users/jzelner/repos/bibtex-library/jz_library.bib
      - epid684/refs.bib
    resource-path: 
          - "images"

execute: 
  freeze: auto