---
date: 3/20/2023
---
# Postcards from the road

In this assignment, I am asking you to take over the class for part of a session (~40m) and use this time to:

1. Share your expertise on your project topic with the class. 

2. Showcase the progress you have made on your project to this point.

3. Get critical feedback on this progress from me and your peers as we head into the final stretch of the semester.

In preparation for your turn leading part of a class session, I am asking you to:

1. Assign a single reading relevant to your project topic, which other members of the class will read beforehand and come to class prepared to discuss. Prior to settling on a reading, I will ask you to send me three candidate papers and I will help you select one that is well-suited to educating the rest of the class about your project area and stimulating discussion.

2. Prepare to lead discussion and/or an in-class activity relevant to your topic area and the assigned reading. This should involve a mini-lecture (5-10m) providing additional background on your topic area that aids in the interpretation of the reading and prompts for discussion. If you would like to run an in-class activity of some kind that goes beyond posing questions to the class as a whole, please feel free to do so! This could involve small groups, writing a short reflection, etc. 

3. Provide a brief update on your project progress (5-10m), identifying both your ongoing successes and sticking points/frustrations which you could use constructive feedback on soliving. 

