---
date: 4/26/2023
---
# Final Product

For your culminating assignment, I am asking you to take a step along the path linking your 
[origin](assignment-origin.qmd) problem to your proposed [destination](assignment-destination.qmd). 

This could be any or the following:

- A proposal for foundation or government funding to implement the approach you have selected in an affected community,
-  An op-ed or blog post making the case for your approach to the public or policymakers,
-  a policy position paper, or a grant proposal for research funds. 

You could also _implement_ a component of your proposed approach by:

- Conducting a spatial data analysis
- Constructing a visually-appealing report or pamphlet to be shared with community members,
- Recording and editing a podcast episode making the case for your approach, making a set of maps, an interactive data visualization, 
- *Or* something else that works for your problem.

**It is OK for the final product to be a work-in-progress at the end of the term.** I would far prefer to see you be ambitious and start something you can continue to carry forward than to narrow your ambitions to meet an end-of-term deadline. 

