---
date: 2/20/2023
publish: true
---

# What is the destination?

With your problem clearly defined in your 
[origin](assignment-origin.qmd) assignment, the next step is to describe in concrete terms what it would look like if your problem was solved or at least meaningfully addressed. This could be reducing incidence of a particular disease in a community, increasing knowledge of risk and protective factors among at-risk individuals, or closing a gap in scientific knowledge of the problem, or something else you identify as being important. 

In other words, I am asking you to *identify a concrete target for improvement* in your problem. This could be quantitative, e.g. a 10% reduction in risk of death from cardiovascular disease in a given community, or something more qualitative. For example, if your identified problem is around a knowledge or data gap rather than reducing disease incidence, it could be focused on developing a scientific study or evaluation project to understand the mechanisms driving your outcome. *Please think broadly about what the nature of the improvement you wish to make is and connect that to the format of your final project.*

This assignment will take the form of an in-class 'lightning' presentation of 8-10m in mid-Feburary. in your presentation, please briefly:

1. Outline the problem and argue for its importance,  

2. Present your target 🎯 for improvement based on your research and understanding of what has already been tried in this area.  

3. Propose a format for your final product that will facilitate making progress towards your identified target. This could be a research paper, a technical report, a blog post, a data visualization, or anything else you think would advance your goal and allow you to develop or showcase your skills.

Because these presentations are necessarily short, we will have limited time for real-time Q&A during this session, but we will use a google doc to keep track of comments and suggestions in real time during the course session. This will give you useful feedback that will help guide your project going forward. 