---
date_created: 2021-12-19
publish: true
---

With your problem clearly defined in your [[What is the origin?|origin]] assignment, the next step is to describe in concrete terms what it would look like if your problem was solved or at least meaningfully addressed. This could be reducing incidence of a particular disease in a community, increasing knowledge of risk and protective factors among at-risk individuals, or closing a gap in scientific knowledge of the problem, or something else you identify as being important. 

In other words, I am asking you to *identify a concrete target for improvement* in your problem. This could be quantitative, e.g. a 10% reduction in risk of death from cardiovascular disease in a given community, or something more qualitative. For example, if your identified problem is around a knowledge or data gap rather than reducing disease incidence, it could be focused on developing a scientific study or evaluation project to understand the mechanisms driving your outcome. 

This assignment will take the form of an in-class presentation prior to the mid-term break in late February in which you will outline the problem and argue for its importance based on your work in the "[[What is the origin?]]" project and feedback from me on this work, and then present your target for improvement based on your research and understanding of what has already been tried in this area. 