---
date_created: 2021-12-19
publish: true
---

For your culminating assignment, I am asking you to take a step along the path linking your [[What is the origin?|'origin']] problem to your [[What is the destination?|'destination']] solution. 

This could be any or the following:

- A proposal for foundation or government funding to implement the approach you have selected in an affected community,
-  An op-ed or blog post making the case for your approach to the public or policymakers,
-  a policy position paper, or a grant proposal for research funds. 

You could also _implement_ a component of your proposed approach by:

- Conducting a spatial data analysis
- Constructing a visually-appealing report or pamphlet to be shared with community members,
- Recording and editing a podcast episode making the case for your approach, making a set of maps, an interactive data visualization, 
- *Or* something else that works for your problem.

In this assignment, I am asking you to _compare_ potential upsides and downsides associated with three potential approaches to your final project. This should be added to the research document you have been compiling over the course of the term, but can otherwise take whatever format you find most useful.  

Be prepared to share this document, as it will be used as the basis for an in-class workshop in which you will discuss your idea with  the class and use our feedback to refine your work in advance of submitting your [[Final Product Submission |final product]].
