---
pagetitle: "Making the case for the water supply"
format: 
    revealjs:
        theme: [solarized, styles.scss]
        incremental: true
        bibliography: /Users/jzelner/repos/bibtex-library/jz_library.bib
        #csl: "../../assets/american-journal-of-epidemiology.csl"
---
{{< include _titleslide.qmd >}}

## Agenda

- Syllabus updates

- General feedback about 'origin assignments'

- Snow's analysis of the Golden Square outbreak

- Hands-on with the Snow data 

## Course Updates/Proposal

- Moving module on multi-level modeling up to next week. 

- Destination assignments now a pre-break (short) presentation.

- Change 'postcards' assignments to be a series of student-run course meetings.

## Updated postcards assignment 📬

- Ask you to assign 1 paper on your topic to the class. 

- Make a short presentation with an overview of the goals of your project, progress so far, and feedback areas from the class.

- Provide discussion questions about the assigned reading for the class and co-lead discussion w/me.

- Aim for 2-3 presentations per session over 4 sessions after spring break. 

# <span class="alert">The Pump!</span> {data-background-image="/images/broad_street_pump.jpg"} 

## Snow searched for exceptions that prove the rule to convince skeptics

> Snow knew that the case would be made in the exceptions to the rule. What he needed now were aberrations, deviations from the norm. <span class="alert">Pockets of life where you would expect death, pockets of death where you would expect life.</span>  [@johnson2007, p.140]


## Snow's experience with anesthesia contributed to his <span class="alert">miasma</span> debunking

> [Snow's] experience with choloform and ether had also endowed [him] with an intuitive grasp of the way that gases disperse in the environment. Ether could be deadly in a concentrated form, delivered directly to the patient’s lungs. <span class="alert">But a doctor delivering it, standing a foot away from the patient, wouldn’t feel its effects in the slightest, because the density of ether molecules in the air dropped at a precipitous rate the farther removed one was from the inhaler itself.</span>  (p.145)

## In pairs/threes: What happened, exactly, in Golden Square?

- What was the most likely route by which cholera was introduced to the Broad Street Pump?

- Why didn't the outbreak spread <span class="alert">exponentially</span>?

- What is the most plausible explanation for why the outbreak ended?

- How did Snow think about and use information about distance to flag the pump as a key source of risk? 

```{r}
library(countdown)
countdown(minutes = 5, warn_when = 60, seconds = 0, play_sound=FALSE)
```


## Put the <span class="alert">mechanism</span> on the map

<div class="toprow">
  <div style="flex:70%"><blockquote style="font-size: 0.6em;">"In his mind snow was already drawing maps. he’d imagined an overview of the Golden Square neighborhood, with a <span class="alert">boundary line running an erratic circle around the Broad Street pump.</span> Every person inside that border lived closer to the poisoned well; everyone outside would have had reason to draw water from a different source." (p. 141)</blockquote></div>
  <div class="textcolumn"><ul>
      <li class="fragment">10 cases outside the boundary.</li>
      <li class="fragment">2 were tailor & son on Cross st.</li>
      <li class="fragment">3 were children who went to school near the pump.</li>
      <li class="fragment">3 more regularly drank from the pump.</li>
      <li class="fragment">2 more could be chalked up to the typical toll of Cholera in a given weekend.</li>
    </ul>
  </div>
  
</div>

## Scale, scale, scale (again!)

> "If the symptoms of the cholera concentrated around the small intestine, then there must be some telltale characteristic in the eating and drinking habits of cholera victims. <span class="alert">If cholera was waterborne, then the patterns of infection must correlate with the patterns of water distribution in London's neighborhoods.</span>" (p. 148)

## Strength of Snow's explanation rested on <span class="alert">nuts and bolts</span> analysis.

- Cesspool in the basement of 40 Broad was the source of the outbreak. 

- Others got sick in 40 Broad over the course of the week, so why did they not add additional fuel to the 🔥?

- Only the Lewis family had access to the basement cesspool, while others threw their waste out the...🪟.

## Modern tools for an old problem 

[https://sph-umich.shinyapps.io/john-snow-cholera](https://sph-umich.shinyapps.io/john-snow-cholera)

## Next Time

## References
