---
title: Caution in interpretation of declining race/ethnic disparities in COVID-19 mortality
format: pdf
pdf-engine: xelatex
bibliography: /Users/jzelner/repos/bibtex-library/jz_library.bib
csl: "../../assets/american-journal-of-epidemiology.csl"
---
In their recent letter published in *JEPH*, Schultes et al. [@schultes2022] examined patterns of declining race/ethnic disparities in COVID-19 mortality in Connecticut from March 2020-December 2021. While this work represents a useful contribution to the expanding literature on race/ethnic and socioeconomic disparities in SARS-CoV-2 mortality, we were concerned by the authors' contention that their "findings suggest that attenuation of racial and ethnic disparities is an achievable public health goal," which we believe reflects a more broadly-held misapprehension about the efficacy of measures focused on combating inequality in pandemic-related mortality.

While changes in the mortality rate ratio (MRR) for non-Whites as compared to Whites may reflect some progress against race/ethnic and class-based disparities SARS-CoV-2 infection and mortality,  a narrow focus on declining group-specific MRRs may paint a far more optimistic picture of this progress than is warranted.

On a methodological level, ratio-based measures of SARS-CoV-2 inequality are susceptible to distortion from change in the denominator. As most studies of race/ethnic disparity use non-Hispanic Whites as the reference group, diminishing rate ratios by race may reflect declines in the numerator (the minoritized group in question) as well as increases in the denominator (an advantaged group, typically Whites). In fact, Lawton et al. found that much of the decline in county-level SARS-CoV-2 MRRs by race were better explained by increasing overall prevalence reflecting increased infection and death among Whites than precipitious declines in infection among non-Whites [@lawton2021].

From a health justice perspective, it is critical that within-pandemic successes in attenuating infection disparities not be conflated with success in combating the racial capitalism [@lasterpirtle2020] and structural racism, which contributed to differential participation in hazardous 'essential work' and other risks [@chang2021] which made such starkly unequal - and irreversible - early-pandemic outcomes inevitable. 

Because of this, comparisons of infection and mortality between race/ethnic and class groups over time should consider both *within-pandemic* changes in response to conditions on the ground, but also *between-pandemic* differences reflecting the influence of structural disparities prior to the outbreak of a novel pathogen. Of course, between-pandemic comparisons are difficult to make because of the - thankfully - relatively rare nature of global pandemics, although there is abundant evidence mortality disparities during the 1918 influenza pandemic [@grantz2016]. 

However, we suggest that, at a minimum, researchers and policymakers contemplate a simple thought experiment before suggesting that secular declines in race/ethnic MRRs suggest progress against infection inequality: If a novel pandemic characterized by similar lethality and transmissibility to SARS-CoV-2 were to emerge in the coming months, would the factors that led to declining MRRs *during* this pandemic translate into dramatically decreased or eliminated disparities in death at the beginning of the next one? We doubt it, and advocate for caution in interpretation of these declines as a result.

# References