---
class: 4
date: "1/17/2023"
---

# Tools for making sense of spatial variation

In this session, we will focus in on the[]() problem of how we can use epidemiological data to examine the role of Tobler's first law - the universality of spatial relatedness - as well as Goodchild's revised first law - the ubiquity of spatial variation - in epidemiology data. 

## Before Class

Please read the following two selections. The first is a short article introducing the concept of a disease 'hotspot' and the second is a more in-depth treatment of the idea of disease clustering:

1. Read the piece ["What is a Hotspot, Anyway?"](https://www.dropbox.com/s/2c9yz5v1ji8h2wt/lessler_et_al_2017_what_is_a_hotspot_anyway.pdf?dl=0) by @lessler2017

2. And [Chapter 3: Interpreting Clusters of Disease Events](https://www.dropbox.com/s/y2fiaf6e08v0412/handbook_of_spatial_epidemiology.pdf?dl=0) from [@lawson2016]


## During Class

During the first half of class, we will discuss the readings and key concepts in them and I will introduce the concept of *kernel smoothing* and its application to epidemiologic data as a tool for visualizing and identifying disease clusters. 

In the second half of class, we will complete a hands-on activity in which we will experiment with smoothing different types of simulated data using this [interactive tutorial](https://sph-umich.shinyapps.io/smoothing).
