# Course Policies

I believe strongly that this course is a collaborative endeavor, and that the primary objective of this class is to help you clarify and achieve your own academic and professional goals. Our course policies are developed with that in mind and with the goal of creating an environment of mutual respect that also fosters intellectual exploration, creativity and productive risk-taking. If at any point you feel that these goals are *not* being met, please do not hesitate to reach out to me directly. 

## Attendance

This class will be held in-person and students are asked and expected to attend in-person whenever possible. If you do need to miss class for whatever reason, please let me know ahead of time so that we can plan accordingly. 

I will record each class session using Zoom and make the link to these recordings available to the entire class. When we have a guest speaker, these sessions will be recorded if the visiting speaker consents.

If you are unable to attend in person but can join via Zoom, that will be an option. However, since the class is heavily focused on discussion, in-class activities, and project work, the utility of these recordings and remote participation will be limited primarily to listening to and reviewing the lecture portions of the class. 

## Assignment Due Dates

Due dates for assignments have been chosen to ensure that there is enough time to give detailed feedback prior to the due date for the next assignment. However, I know that life often intervenes in the form of either personal obligations or other assignments which can make it difficult to get every assignment in on time. If you do not anticipate being able to make a due date, please let me know as far ahead of time as possible so that we can arrange an extension.

## Assessment & Grading

I believe that detailed, qualitative feedback from instructors and peers is far more useful than numerical grading. Numerical grading schemes disincentivize exploration and risk-taking,  rewarding consistency over the course of a term over growth. Assignment assessments and final grades for this course are constructed with the goal of facilitating growth and exploration within a student-centered environment. This, of course, entails a slightly different set of expectations and responsibilities for students and instructors than in a course following a classic grading/assessment scheme. 

## Assignment Grades

There will be no numerical or letter grades given for written assignments or presentations, including the final product of your semester-long project. Instead, you will receive written feedback from me on each assignment, and will also have a number of opportunities to share your ideas and receive constructive feedback from your classmates. 

This will include in-class presentations on your research topic, structured peer-reviews of work-in-progress, in-class 'workshop' time to work with your project group and get advice from me and your classmates, as well as periodic self-assessments that you will submit to me. 

Following fall break, I will ask you to submit responses to a midterm check-in survey, which will allow me to better understand what is working and not working for you in the class so that we can make adjustments for the second half of the term.

> [!NOTE] For peer and self-assessments, I will provide a template containing an outline of the areas I am asking you to give feedback on. These assessment opportunities are meant to help keep you on track and to flag individual and collective issues (i.e. unclear assignment instructions, questions about assignment topics, format, etc. as they arise). 

## Semester Grades

Final course grades will be self-assigned and based on each student's assessment of their progress towards their self-identified goals as well as those identified by me over the course of the term. I reserve the right to revise final grades upwards or downwards if necessary, but will only do this only in rare cases where a student's self-assessed grade is strongly out of alignment with my perception of their performance in the course, and in all others will take the student's self-assessed grade as-is. 

:::{.callout-important}

## Exceptions to self-grading

The primary factors that would result in a downward revision of a student's self-assessed grade are 1) chronic, unexplained lateness in turning in assignments or not completing assignments, 2) instances of academic dishonesty.
:::

While consistent in-person attendance is expected, I understand that personal, professional and academic circumstances may periodically impact your ability to attend either in-person or remotely. I will not take attendance during regular course sessions and an excused absence is not required on most days. 

:::{.callout-important}

## In-class presentations and feedback 

However, on days when students are presenting and giving/receiving feedback, attendance or an excused absence is required and unexplained/excused absence may result in a downward revision of your final grade. This requirement reflects a recognition that on these days of class, individual attendance impacts all course members. 
:::

Students are also welcome to take the course under the [Satisfactory/Unsatisfactory](https://sph.umich.edu/admissions/policies-procedures/mph-mhsa.html) (S/U) grading scheme offered by SPH if desired.