# Postcards from the Road

## Session 1 (3/14){#session-1}

[JZ Slides](slides/postcards_session_1.qmd)

### Brooke 

Laybohr Kamara I, Wang L, Guo Y, et al. Spatial–temporal heterogeneity and determinants of HIV prevalence in the Mano River Union countries. Infectious Diseases of Poverty. 2022;11(1):116. doi:10.1186/s40249-022-01036-1

### Levy

Clarke P, George LK. The Role of the Built Environment in the Disablement Process. Am J Public Health. 2005;95(11):1933-1939. doi:10.2105/AJPH.2004.054494

## Session 2 (3/16){#session-2}

### Kaitlin

Stopka, T. J., Amaravadi, H., Kaplan, A. R., Hoh, R., Bernson, D., Chui, K. K. H., Land, T., Walley, A. Y., LaRochelle, M. R., & Rose, A. J. (2019). Opioid overdose deaths and potentially inappropriate opioid prescribing practices (PIP): A Spatial Epidemiological Study. International Journal of Drug Policy, 68, 37–45. https://doi.org/10.1016/j.drugpo.2019.03.024

### Victoria

Finlay J, Esposito M, Langa KM, Judd S, Clarke P. Cognability: An Ecological Theory of neighborhoods and cognitive aging. Social Science & Medicine. 2022;309:115220. doi:10.1016/j.socscimed.2022.115220

## Session 3 (3/21){#session-3}

### Chloe

Fralick M, Nott C, Moggridge J, et al. Detection of Covid-19 Outbreaks Using Built Environment Testing for SARS-CoV-2. NEJM Evidence. Published online February 17, 2023. [doi:10.1056/EVIDoa2200203](https://doi.org/10.1056/EVIDoa2200203)

[Slides](https://www.dropbox.com/s/kp3uavydq0zwvl9/chloe_postcards_presentation.pptx?dl=0)

### Mackenzie

Kaufman, E. J., Morrison, C. N., Branas, C. C., & Wiebe, D. J. (2018). State firearm laws and interstate firearm deaths from homicide and suicide in the United States: a cross-sectional analysis of data by county. JAMA Internal Medicine, 178(5), 692-700. doi:10.1001/jamainternmed.2018.0190

## Session 4 (3/23){#session-4}

### Aaron 

Bharti N, Tatem AJ, Ferrari MJ, Grais RF, Djibo A, Grenfell BT. Explaining Seasonal Fluctuations of Measles in Niger Using Nighttime Lights Imagery. Science. 2011;334(6061):1424-1427. doi:10.1126/science.1210554

### Sasha

Brooks MM, Siegel SD, Curriero FC. Characterizing the spatial relationship between smoking status and tobacco retail exposure: Implications for policy development and evaluation. Health & Place. 2021;68:102530. doi:10.1016/j.healthplace.2021.102530
