# Miasma vs. Germ Theory

In this session, we will discuss the competing causal explanations for infection during the London Cholera Outbreak, specifically _miasma_ theory, which posited that infection was transmitted solely via noxious air, and _germ_ theory, which posited that there was an infectious agent transmitted from person to person. One of the big takeaways from this session's readings is that Snow used spatial information to make the argument that observed spatial patterns of Cholera could not be explained well at all by miasma theory, but instead was more consistent with the _transmission_ of some infectious agent, i.e. _V. Cholerae_. 

## Before Class

Continue reading *The Ghost Map, Ch 3-4 (pp 56-109)* [@johnson2007]

## During Class

We will begin to explore the concept of a _natural experiment,_ which is what Snow's _experimenta crucis_ (described in the readings) was an early example of. We will discuss both how such studies can be valuable, and also how they can go wrong, or at least open up a number of questions while answering others.

## Additional Resources

[Slides](slides/session_6_miasma.qmd)