---
pagetitle: "Destination project workshop"
---

# 'Destination' project workshop

The goal of today's class session is to digest feedback from the lightning presentations on tuesday and to use this feedback to make a plan for your project going forward over the rest of the term. 

:::{.callout-tip}
## Our goal is to finish class today with a clear and concise proposal for your final project.

We are going to use this session to help solidify your overarching goals for your project and to translate that into a **concrete** proposal about the focus and format of your final product. 
:::


## Agenda

1. On your own: Review comments and feedback from your presentation. (~20m)

    a. Address and respond to comments in the document about areas of confusion and suggestions for your final project.

    b. Has this feedback and discussion changed your thinking about what your final product should be? If so, how?

    c. In this document, write up a 1-2 paragraph proposal for your final product, including a short, descriptive title. Include information on:

        i. **What public health outcomes would you like to impact with your project?** The project is likely just  one step along a longer path to that impact, but it keeping these goals in mind will help you be specific about what you want to and to orient towards achieving those longer-term goals. *Don't be bashful about being ambitious and expansive here!*

        ii. **Who is the ideal audience for your work?** Is this information most useful for the general public? For a specialist scientific audience? For working public health professionals? Policymakers? Someone else? All of the above?

        ii. **What format do you think will work best for your work?** This could be a policy brief, a research paper, a data visualization, a blog post, a podcast episode, or anything else that matches the goals of the project with the audience you identified above. *Think about this in terms of both public health and personal/professional interest: Is there a particular format that will help you either acheive an academic goal or showcase your skills and experience to practice partners/employers?*

        iii. **What is feasible this term?** Given the time we have left, what should the scope of the project be for the rest of the term? Do you envision continuing this work after the semester ends? How does that impact your planning?

2. Pitch your proposal and get peer feedback (~40m)

    a. In groups of four, each  member will briefly summarize their response to the original peer feedback and briefly explain and advocate for their final project idea to the group.

    b. Group members will read each pitch and provide comments in the document during the discussion.

3. Revise your proposal (~20m)

    a. Based on the feedback from your small-group discussions, make any revisions you think are necessary to your final proposal.

    b. During this time, I will also come around and check in with you individually.

## Resources

[Feedback document](https://docs.google.com/document/d/10treg88Hxa7mEo7YhDTb8KpV-V3e3yj1OtqhDJ4Fv6U/edit?usp=sharing)
